paths:
  source_folder: 'Assets/'
  json_source_file: 'data.json'
  json_destination_file: 'data_mod2.json'
  yaml_destination_file: 'data_ymod2.yaml'

queue:
  0:
    action: 'jsonDeserialization'
    active: True
  1:
    action: 'jsonSerialization'
    active: True
    type: object
  2:
    action: 'jsonSerialization'
    active: True
    type: file
  3:
    action: 'yamlConversion'
    active: True
    type: object
  4:
    action: 'yamlConversion'
    active: True
    type: file